/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DoanhThu;

/**
 *
 * @author pc
 */
public class Thongkedoanhthu extends javax.swing.JFrame {

    
    public Thongkedoanhthu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1_139 = new javax.swing.JPanel();
        jLabel1_139 = new javax.swing.JLabel();
        jPanel2_139 = new javax.swing.JPanel();
        jLabel2_139 = new javax.swing.JLabel();
        jTextField1_139 = new javax.swing.JTextField();
        jButton1_139 = new javax.swing.JButton();
        jButton2_139 = new javax.swing.JButton();
        jButton3_139 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_139 = new javax.swing.JTable();
        jPanel4_139 = new javax.swing.JPanel();
        jLabel3_139 = new javax.swing.JLabel();
        jTextField2_139 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1_139.setBackground(new java.awt.Color(0, 153, 0));

        jLabel1_139.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1_139.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1_139.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_139.setText("THỐNG KÊ DOANH THU");

        javax.swing.GroupLayout jPanel1_139Layout = new javax.swing.GroupLayout(jPanel1_139);
        jPanel1_139.setLayout(jPanel1_139Layout);
        jPanel1_139Layout.setHorizontalGroup(
            jPanel1_139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1_139Layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(jLabel1_139)
                .addGap(197, 197, 197))
        );
        jPanel1_139Layout.setVerticalGroup(
            jPanel1_139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1_139Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1_139)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2_139.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2_139.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2_139.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2_139.setText("Tìm kiếm theo ngày");

        jButton1_139.setBackground(new java.awt.Color(255, 255, 255));
        jButton1_139.setText("Tìm kiếm");

        jButton2_139.setBackground(new java.awt.Color(255, 255, 255));
        jButton2_139.setText("Refresh");

        jButton3_139.setBackground(new java.awt.Color(255, 255, 255));
        jButton3_139.setText("Cancel");
        jButton3_139.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_139ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2_139Layout = new javax.swing.GroupLayout(jPanel2_139);
        jPanel2_139.setLayout(jPanel2_139Layout);
        jPanel2_139Layout.setHorizontalGroup(
            jPanel2_139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_139Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2_139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2_139Layout.createSequentialGroup()
                        .addComponent(jLabel2_139)
                        .addGap(41, 41, 41)
                        .addComponent(jTextField1_139, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2_139Layout.createSequentialGroup()
                        .addComponent(jButton1_139)
                        .addGap(45, 45, 45)
                        .addComponent(jButton2_139)
                        .addGap(50, 50, 50)
                        .addComponent(jButton3_139)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2_139Layout.setVerticalGroup(
            jPanel2_139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_139Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2_139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2_139)
                    .addComponent(jTextField1_139, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2_139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2_139)
                    .addComponent(jButton1_139)
                    .addComponent(jButton3_139))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1_139.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã hoá đơn", "Ngày đặt", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(jTable1_139);

        jPanel4_139.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3_139.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3_139.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3_139.setText("Tổng doanh thu ");

        javax.swing.GroupLayout jPanel4_139Layout = new javax.swing.GroupLayout(jPanel4_139);
        jPanel4_139.setLayout(jPanel4_139Layout);
        jPanel4_139Layout.setHorizontalGroup(
            jPanel4_139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4_139Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3_139)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2_139, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4_139Layout.setVerticalGroup(
            jPanel4_139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4_139Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4_139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3_139)
                    .addComponent(jTextField2_139, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel4_139, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4_139, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1_139, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2_139, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1_139, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2_139, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3_139ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_139ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3_139ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Thongkedoanhthu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Thongkedoanhthu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Thongkedoanhthu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Thongkedoanhthu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Thongkedoanhthu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_139;
    private javax.swing.JButton jButton2_139;
    private javax.swing.JButton jButton3_139;
    private javax.swing.JLabel jLabel1_139;
    private javax.swing.JLabel jLabel2_139;
    private javax.swing.JLabel jLabel3_139;
    private javax.swing.JPanel jPanel1_139;
    private javax.swing.JPanel jPanel2_139;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4_139;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_139;
    private javax.swing.JTextField jTextField1_139;
    private javax.swing.JTextField jTextField2_139;
    // End of variables declaration//GEN-END:variables
}
