/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trangchu.form;

import Trangchu.main.Main;

/**
 *
 * @author RAVEN
 */
public class Form_doanhthu extends javax.swing.JPanel {

    /**
     * Creates new form Form_1
     */
    public Form_doanhthu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel2_139 = new javax.swing.JPanel();
        button1_139 = new Quanlysanpham.Button();
        button2_139 = new Quanlysanpham.Button();
        button4_139 = new Quanlysanpham.Button();
        jTextField139 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_139 = new javax.swing.JTable();
        jPanel4_139 = new javax.swing.JPanel();
        jLabel3_139 = new javax.swing.JLabel();
        jTextField2_139 = new javax.swing.JTextField();
        header1_139 = new doanhthu.header();

        jButton5.setText("jButton1");

        setBackground(new java.awt.Color(242, 242, 242));

        jPanel2_139.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        button1_139.setText("Tìm kiếm");

        button2_139.setText("Refresh");
        button2_139.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2_139ActionPerformed(evt);
            }
        });

        button4_139.setText("Home");
        button4_139.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button4_139MouseClicked(evt);
            }
        });
        button4_139.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4_139ActionPerformed(evt);
            }
        });

        jTextField139.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm theo ngày"));
        jTextField139.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField139ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2_139Layout = new javax.swing.GroupLayout(jPanel2_139);
        jPanel2_139.setLayout(jPanel2_139Layout);
        jPanel2_139Layout.setHorizontalGroup(
            jPanel2_139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_139Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2_139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField139, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2_139Layout.createSequentialGroup()
                        .addComponent(button1_139, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(button2_139, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(button4_139, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2_139Layout.setVerticalGroup(
            jPanel2_139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2_139Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTextField139, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2_139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button1_139, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2_139, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button4_139, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1_139.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "So hoa don", "thoi gian", "ngay hd", "ma KH", "tri gia"
            }
        ));
        jScrollPane1.setViewportView(jTable1_139);

        jPanel4_139.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3_139.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3_139.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3_139.setText("Tổng doanh thu ");

        javax.swing.GroupLayout jPanel4_139Layout = new javax.swing.GroupLayout(jPanel4_139);
        jPanel4_139.setLayout(jPanel4_139Layout);
        jPanel4_139Layout.setHorizontalGroup(
            jPanel4_139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4_139Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3_139)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2_139, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4_139Layout.setVerticalGroup(
            jPanel4_139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4_139Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4_139Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3_139)
                    .addComponent(jTextField2_139, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2_139, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
            .addComponent(header1_139, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4_139, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header1_139, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2_139, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4_139, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void button4_139MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4_139MouseClicked
        this.setVisible(false);
        new Main().setVisible(true);
    }//GEN-LAST:event_button4_139MouseClicked

    private void button4_139ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4_139ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button4_139ActionPerformed

    private void button2_139ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2_139ActionPerformed
        // TODO add your handling code here:
        jTextField139.setText("");
    }//GEN-LAST:event_button2_139ActionPerformed

    private void jTextField139ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField139ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField139ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Quanlysanpham.Button button1_139;
    private Quanlysanpham.Button button2_139;
    private Quanlysanpham.Button button4_139;
    private doanhthu.header header1_139;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel3_139;
    private javax.swing.JPanel jPanel2_139;
    private javax.swing.JPanel jPanel4_139;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_139;
    private javax.swing.JTextField jTextField139;
    private javax.swing.JTextField jTextField2_139;
    // End of variables declaration//GEN-END:variables
}
