/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trangchu.form;

import Quanlynhanvien.NhanVienModify;
import Quanlynhanvien.NhanVien_DAO;
import Quanlytaikhoan.model.KhachhangModify;
import Quanlytaikhoan.model.khachhang_DAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAVEN
 */
public class Form_qltk extends javax.swing.JPanel {

    DefaultTableModel tableModel;
    DefaultTableModel tableModelNhanVien;
    /**
     * Creates new form Form_1
     */
    List<khachhang_DAO> KhachhangList = new ArrayList<>();
    List<NhanVien_DAO> NhanVienList = new ArrayList<>();

    public Form_qltk() {
        initComponents();

        tableModel = (DefaultTableModel) tblkhachhang.getModel();
        tableModelNhanVien = (DefaultTableModel) jTblNV.getModel();
        showKH();
        showNhanVien();
    }

    private void showKH() {
        KhachhangList = KhachhangModify.findAll();

        tableModel.setRowCount(0);

        for (khachhang_DAO kh : KhachhangList) {
            tableModel.addRow(new Object[]{tableModel.getRowCount() + 1, kh.getUserName(), kh.getEmail(),
                kh.getGioi_tinh(), kh.getSo_dien_thoai(), kh.getTuoi()});

        }

    }

    private void showNhanVien() {
        NhanVienList = NhanVienModify.findAll();
        tableModelNhanVien.setRowCount(0);
        for (NhanVien_DAO nv : NhanVienList) {
            if (nv.getGt().equals("1")) {
                tableModelNhanVien.addRow(new Object[]{nv.getIdnv(), nv.getTennv(),
                    nv.getEmail(), nv.getSdt(), "Nam"});
            } else {
                tableModelNhanVien.addRow(new Object[]{nv.getIdnv(), nv.getTennv(),
                    nv.getEmail(), nv.getSdt(), "Nữ"});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        panelBorder1 = new Quanlytaikhoan.swing.PanelBorder();
        bodyPane = new Quanlytaikhoan.swing.PanelBorder();
        materialTabbed1 = new Quanlytaikhoan.component.MaterialTabbed();
        KHPane = new javax.swing.JPanel();
        txttuoi = new Quanlytaikhoan.component.TextField();
        txtName = new Quanlytaikhoan.component.TextField();
        txtmail = new Quanlytaikhoan.component.TextField();
        txtsdt = new Quanlytaikhoan.component.TextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblkhachhang = new javax.swing.JTable();
        btndel = new Quanlytaikhoan.component.Button();
        btnsave = new Quanlytaikhoan.component.Button();
        cbgioitinh = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnreset = new Quanlytaikhoan.component.Button();
        NVPane = new javax.swing.JPanel();
        txtIdNV = new Quanlytaikhoan.component.TextField();
        txtTenNV = new Quanlytaikhoan.component.TextField();
        txtEmail = new Quanlytaikhoan.component.TextField();
        txtSDT = new Quanlytaikhoan.component.TextField();
        button6 = new Quanlytaikhoan.component.Button();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblNV = new javax.swing.JTable();
        button8 = new Quanlytaikhoan.component.Button();
        button9 = new Quanlytaikhoan.component.Button();
        button10 = new Quanlytaikhoan.component.Button();
        cbgioitinhNV = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        panelBorder2 = new Quanlytaikhoan.swing.PanelBorder();
        searchBar_54 = new Quanlytaikhoan.component.TextFieldAnimation();
        comboBoxSuggestion1 = new Quanlytaikhoan.component.ComboBoxSuggestion();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        detailInfoPane = new javax.swing.JPanel();
        detailInfoKHPane = new Quanlytaikhoan.swing.PanelBorder();
        textFieldSuggestion1 = new Quanlytaikhoan.component.TextFieldSuggestion();
        jLabel4 = new javax.swing.JLabel();
        textFieldSuggestion2 = new Quanlytaikhoan.component.TextFieldSuggestion();
        jLabel5 = new javax.swing.JLabel();
        textFieldSuggestion3 = new Quanlytaikhoan.component.TextFieldSuggestion();
        jLabel6 = new javax.swing.JLabel();
        textFieldSuggestion4 = new Quanlytaikhoan.component.TextFieldSuggestion();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textFieldSuggestion5 = new Quanlytaikhoan.component.TextFieldSuggestion();
        jLabel9 = new javax.swing.JLabel();
        radioButtonCustom5 = new Quanlytaikhoan.component.RadioButtonCustom();
        radioButtonCustom6 = new Quanlytaikhoan.component.RadioButtonCustom();
        button11 = new Quanlytaikhoan.component.Button();
        button12 = new Quanlytaikhoan.component.Button();
        detailInfoNVPane = new Quanlytaikhoan.swing.PanelBorder();
        textFieldSuggestion6 = new Quanlytaikhoan.component.TextFieldSuggestion();
        jLabel10 = new javax.swing.JLabel();
        textFieldSuggestion7 = new Quanlytaikhoan.component.TextFieldSuggestion();
        jLabel11 = new javax.swing.JLabel();
        textFieldSuggestion8 = new Quanlytaikhoan.component.TextFieldSuggestion();
        jLabel12 = new javax.swing.JLabel();
        textFieldSuggestion9 = new Quanlytaikhoan.component.TextFieldSuggestion();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        textFieldSuggestion10 = new Quanlytaikhoan.component.TextFieldSuggestion();
        jLabel15 = new javax.swing.JLabel();
        radioButtonCustom7 = new Quanlytaikhoan.component.RadioButtonCustom();
        radioButtonCustom8 = new Quanlytaikhoan.component.RadioButtonCustom();
        button13 = new Quanlytaikhoan.component.Button();
        button14 = new Quanlytaikhoan.component.Button();
        menu1 = new Quanlytaikhoan.component.Menu();

        jButton5.setText("jButton1");

        setBackground(new java.awt.Color(242, 242, 242));

        panelBorder1.setBackground(new java.awt.Color(249, 249, 249));
        panelBorder1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bodyPane.setBackground(new java.awt.Color(249, 249, 249));

        materialTabbed1.setBackground(new java.awt.Color(249, 249, 249));
        materialTabbed1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        KHPane.setBackground(new java.awt.Color(249, 249, 249));
        KHPane.setOpaque(false);

        txttuoi.setLabelText("Tuổi");

        txtName.setLabelText("Tên khách hàng");

        txtmail.setLabelText("Email");

        txtsdt.setLabelText("Số điện thoại");

        tblkhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Tên", "Email", "Giới tính", "SDT", "Tuổi"
            }
        ));
        jScrollPane1.setViewportView(tblkhachhang);

        btndel.setText("Xoá");
        btndel.setBoderColor(new java.awt.Color(204, 0, 0));
        btndel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        btnsave.setText("Lưu");
        btnsave.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        cbgioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", " " }));

        jLabel1.setText("Giới tính");

        btnreset.setText("Reset");
        btnreset.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KHPaneLayout = new javax.swing.GroupLayout(KHPane);
        KHPane.setLayout(KHPaneLayout);
        KHPaneLayout.setHorizontalGroup(
            KHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KHPaneLayout.createSequentialGroup()
                .addGroup(KHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KHPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(KHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btndel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(KHPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(KHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(KHPaneLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(360, 360, 360))
                                .addGroup(KHPaneLayout.createSequentialGroup()
                                    .addComponent(txtmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(137, 137, 137)))
                            .addGroup(KHPaneLayout.createSequentialGroup()
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(137, 137, 137)))
                        .addGroup(KHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KHPaneLayout.createSequentialGroup()
                                .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                            .addGroup(KHPaneLayout.createSequentialGroup()
                                .addComponent(txttuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        KHPaneLayout.setVerticalGroup(
            KHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KHPaneLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(KHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(KHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(KHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(KHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KHPaneLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(KHPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        materialTabbed1.addTab("Khách Hàng", KHPane);

        NVPane.setOpaque(false);

        txtIdNV.setLabelText("ID Nhân Viên");

        txtTenNV.setLabelText("Tên Nhân Viên");

        txtEmail.setLabelText("Email");

        txtSDT.setLabelText("Số điện thoại");

        button6.setText("Thêm Tài khoản");
        button6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        jTblNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Email", "SDT", "Giới tính"
            }
        ));
        jTblNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblNVMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTblNV);

        button8.setText("Sửa");
        button8.setBoderColor(new java.awt.Color(249, 255, 0));
        button8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });

        button9.setText("Xoá");
        button9.setBoderColor(new java.awt.Color(204, 0, 0));
        button9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });

        button10.setText("Xem chi tiết");
        button10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        cbgioitinhNV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", " " }));

        jLabel2.setText("Giới tính");

        javax.swing.GroupLayout NVPaneLayout = new javax.swing.GroupLayout(NVPane);
        NVPane.setLayout(NVPaneLayout);
        NVPaneLayout.setHorizontalGroup(
            NVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NVPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NVPaneLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(NVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(button8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(button10, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NVPaneLayout.createSequentialGroup()
                        .addGroup(NVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtIdNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(NVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))
                    .addGroup(NVPaneLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbgioitinhNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        NVPaneLayout.setVerticalGroup(
            NVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NVPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NVPaneLayout.createSequentialGroup()
                        .addComponent(txtIdNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NVPaneLayout.createSequentialGroup()
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(NVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NVPaneLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(NVPaneLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(NVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbgioitinhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        materialTabbed1.addTab("Nhân viên", NVPane);

        panelBorder2.setBackground(new java.awt.Color(249, 249, 249));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        detailInfoPane.setLayout(new java.awt.CardLayout());

        detailInfoKHPane.setBackground(new java.awt.Color(249, 249, 249));

        jLabel4.setText("ID : ");

        jLabel5.setText("Tên KH :");

        jLabel6.setText("Mật Khẩu : ");

        jLabel7.setText("Email :");

        jLabel8.setText("Số ĐT :");

        jLabel9.setText("Giới Tính :");

        radioButtonCustom5.setText("Nam");
        radioButtonCustom5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonCustom5ActionPerformed(evt);
            }
        });

        radioButtonCustom6.setText("Nữ");

        button11.setText("Xoá");

        button12.setText("Xác Nhận");

        javax.swing.GroupLayout detailInfoKHPaneLayout = new javax.swing.GroupLayout(detailInfoKHPane);
        detailInfoKHPane.setLayout(detailInfoKHPaneLayout);
        detailInfoKHPaneLayout.setHorizontalGroup(
            detailInfoKHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailInfoKHPaneLayout.createSequentialGroup()
                .addGroup(detailInfoKHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailInfoKHPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldSuggestion3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detailInfoKHPaneLayout.createSequentialGroup()
                        .addGroup(detailInfoKHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(detailInfoKHPaneLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailInfoKHPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(detailInfoKHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldSuggestion2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(textFieldSuggestion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(detailInfoKHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailInfoKHPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(detailInfoKHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailInfoKHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailInfoKHPaneLayout.createSequentialGroup()
                        .addComponent(radioButtonCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(radioButtonCustom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detailInfoKHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textFieldSuggestion5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldSuggestion4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailInfoKHPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(button11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(button12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        detailInfoKHPaneLayout.setVerticalGroup(
            detailInfoKHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailInfoKHPaneLayout.createSequentialGroup()
                .addGroup(detailInfoKHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailInfoKHPaneLayout.createSequentialGroup()
                        .addGroup(detailInfoKHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldSuggestion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailInfoKHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldSuggestion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailInfoKHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldSuggestion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(detailInfoKHPaneLayout.createSequentialGroup()
                        .addGroup(detailInfoKHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldSuggestion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailInfoKHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldSuggestion5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailInfoKHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(detailInfoKHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radioButtonCustom6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(radioButtonCustom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(detailInfoKHPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        detailInfoPane.add(detailInfoKHPane, "card2");

        detailInfoNVPane.setBackground(new java.awt.Color(249, 249, 249));

        jLabel10.setText("ID : ");

        jLabel11.setText("Tên KH :");

        jLabel12.setText("Mật Khẩu : ");

        jLabel13.setText("Email :");

        jLabel14.setText("Số ĐT :");

        jLabel15.setText("Giới Tính :");

        radioButtonCustom7.setText("Nam");
        radioButtonCustom7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonCustom7ActionPerformed(evt);
            }
        });

        radioButtonCustom8.setText("Nữ");

        button13.setText("Xoá");

        button14.setText("Xác Nhận");

        javax.swing.GroupLayout detailInfoNVPaneLayout = new javax.swing.GroupLayout(detailInfoNVPane);
        detailInfoNVPane.setLayout(detailInfoNVPaneLayout);
        detailInfoNVPaneLayout.setHorizontalGroup(
            detailInfoNVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailInfoNVPaneLayout.createSequentialGroup()
                .addGroup(detailInfoNVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailInfoNVPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textFieldSuggestion8, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detailInfoNVPaneLayout.createSequentialGroup()
                        .addGroup(detailInfoNVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(detailInfoNVPaneLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, detailInfoNVPaneLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(detailInfoNVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldSuggestion7, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                            .addComponent(textFieldSuggestion6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(detailInfoNVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(detailInfoNVPaneLayout.createSequentialGroup()
                        .addGroup(detailInfoNVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(detailInfoNVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailInfoNVPaneLayout.createSequentialGroup()
                        .addComponent(radioButtonCustom7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(radioButtonCustom8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(detailInfoNVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textFieldSuggestion10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFieldSuggestion9, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, detailInfoNVPaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(button13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(button14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        detailInfoNVPaneLayout.setVerticalGroup(
            detailInfoNVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailInfoNVPaneLayout.createSequentialGroup()
                .addGroup(detailInfoNVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailInfoNVPaneLayout.createSequentialGroup()
                        .addGroup(detailInfoNVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldSuggestion6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailInfoNVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldSuggestion7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailInfoNVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldSuggestion8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(detailInfoNVPaneLayout.createSequentialGroup()
                        .addGroup(detailInfoNVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldSuggestion9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailInfoNVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldSuggestion10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(detailInfoNVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(detailInfoNVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(radioButtonCustom8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(radioButtonCustom7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(detailInfoNVPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        detailInfoPane.add(detailInfoNVPane, "card2");

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorder2Layout.createSequentialGroup()
                                .addComponent(searchBar_54, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxSuggestion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(detailInfoPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBar_54, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxSuggestion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailInfoPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        materialTabbed1.addTab("Lọc / Tìm Kiếm", panelBorder2);

        javax.swing.GroupLayout bodyPaneLayout = new javax.swing.GroupLayout(bodyPane);
        bodyPane.setLayout(bodyPaneLayout);
        bodyPaneLayout.setHorizontalGroup(
            bodyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(materialTabbed1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(menu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        bodyPaneLayout.setVerticalGroup(
            bodyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPaneLayout.createSequentialGroup()
                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(materialTabbed1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBorder1.add(bodyPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonCustom5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonCustom5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonCustom5ActionPerformed

    private void radioButtonCustom7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonCustom7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioButtonCustom7ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        if (txtIdNV.getText().isEmpty()
                || txtTenNV.getText().isEmpty()
                || txtSDT.getText().isEmpty()
                || txtEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn phải nhập thông tin đầy đủ trước khi cập nhật nhân viên!");
            return;
        }
        int idNhanVien = 0;
        try {
            idNhanVien = Integer.parseInt(txtIdNV.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Mã nhân viên phải là một số nguyên!");
            return;
        }
        String tennv = txtTenNV.getText();
        String gt = cbgioitinhNV.getSelectedItem().toString();
        String sdt = txtSDT.getText();
        String email = txtEmail.getText();
        NhanVien_DAO nv = new NhanVien_DAO(idNhanVien, tennv, email, sdt, gt);
        try{
            NhanVienModify.update(nv);
            JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thành công!");
            showNhanVien();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Cập nhật nhân viên không thành công!");
        }

    }//GEN-LAST:event_button8ActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed

        txtName.setText("");
        txtmail.setText("");
        txtsdt.setText("");
        cbgioitinh.setSelectedIndex(0);
        txttuoi.setText("");
        showKH();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed

        String UserName = txtName.getText();
        String Email = txtmail.getText();
        String gioi_tinh = cbgioitinh.getSelectedItem().toString();
        String so_dien_thoai = txtsdt.getText();
        int Tuoi = Integer.parseInt(txttuoi.getText());
        khachhang_DAO kh = new khachhang_DAO(UserName, Email, gioi_tinh, so_dien_thoai, Tuoi);

        KhachhangModify.insert(kh);
        showKH();
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        int selectedIndex = tblkhachhang.getSelectedRow();
        if (selectedIndex >= 0) {
            khachhang_DAO kh = KhachhangList.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Ban co muon xoa?");
            System.out.println("option : " + option);

            if (option == 0) {
                KhachhangModify.delete(kh.getMa_khach_hang());

                showKH();
            }
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        if (txtIdNV.getText().isEmpty()
                || txtTenNV.getText().isEmpty()
                || txtEmail.getText().isEmpty()
                || txtSDT.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn phải nhập thông tin đầy đủ trước khi thêm nhân viên!");
            return;
        }
        int idNhanVien = 0;
        try {
            idNhanVien = Integer.parseInt(txtIdNV.getText());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Mã nhân viên phải là một số nguyên!");
            return;
        }
        for (NhanVien_DAO nv : NhanVienList) {
            if (nv.getIdnv() == idNhanVien) {
                JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại!");
                return;
            }
        }
        String tennv = txtTenNV.getText();
        String gt = cbgioitinhNV.getSelectedItem().toString();
        String sdt = txtSDT.getText();
        String email = txtEmail.getText();
        NhanVien_DAO nv = new NhanVien_DAO(idNhanVien, tennv, email, sdt, gt);
        try{
            NhanVienModify.insert(nv);
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công!");
            showNhanVien();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Thêm nhân viên không thành công!");
        }
    }//GEN-LAST:event_button6ActionPerformed

    private void jTblNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblNVMouseClicked
        try {
            int row = jTblNV.getSelectedRow();
            txtIdNV.setText((jTblNV.getModel().getValueAt(row, 0).toString()));
            txtTenNV.setText((jTblNV.getModel().getValueAt(row, 1).toString()));
            txtEmail.setText((jTblNV.getModel().getValueAt(row, 2).toString()));
            txtSDT.setText((jTblNV.getModel().getValueAt(row, 3).toString()));
            cbgioitinhNV.setSelectedItem((jTblNV.getModel().getValueAt(row, 4).toString()));
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jTblNVMouseClicked

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:                                  
        if (txtIdNV.getText() == null || txtIdNV.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn phải chọn nhân viên trước khi xoá!");
            return;
        }
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xoá nhân viên này không?", "Thông báo", dialogButton);
        if (dialogResult == 0) {
            try {
                NhanVienModify.delete(Integer.parseInt(txtIdNV.getText()));
                JOptionPane.showMessageDialog(this, "Xóa nhân viên thành công!");
                showNhanVien();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Xóa nhân viên không thành công!");
            }
        }
    }//GEN-LAST:event_button9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel KHPane;
    private javax.swing.JPanel NVPane;
    private Quanlytaikhoan.swing.PanelBorder bodyPane;
    private Quanlytaikhoan.component.Button btndel;
    private Quanlytaikhoan.component.Button btnreset;
    private Quanlytaikhoan.component.Button btnsave;
    private Quanlytaikhoan.component.Button button10;
    private Quanlytaikhoan.component.Button button11;
    private Quanlytaikhoan.component.Button button12;
    private Quanlytaikhoan.component.Button button13;
    private Quanlytaikhoan.component.Button button14;
    private Quanlytaikhoan.component.Button button6;
    private Quanlytaikhoan.component.Button button8;
    private Quanlytaikhoan.component.Button button9;
    private javax.swing.JComboBox<String> cbgioitinh;
    private javax.swing.JComboBox<String> cbgioitinhNV;
    private Quanlytaikhoan.component.ComboBoxSuggestion comboBoxSuggestion1;
    private Quanlytaikhoan.swing.PanelBorder detailInfoKHPane;
    private Quanlytaikhoan.swing.PanelBorder detailInfoNVPane;
    private javax.swing.JPanel detailInfoPane;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTblNV;
    private Quanlytaikhoan.component.MaterialTabbed materialTabbed1;
    private Quanlytaikhoan.component.Menu menu1;
    private Quanlytaikhoan.swing.PanelBorder panelBorder1;
    private Quanlytaikhoan.swing.PanelBorder panelBorder2;
    private Quanlytaikhoan.component.RadioButtonCustom radioButtonCustom5;
    private Quanlytaikhoan.component.RadioButtonCustom radioButtonCustom6;
    private Quanlytaikhoan.component.RadioButtonCustom radioButtonCustom7;
    private Quanlytaikhoan.component.RadioButtonCustom radioButtonCustom8;
    private Quanlytaikhoan.component.TextFieldAnimation searchBar_54;
    private javax.swing.JTable tblkhachhang;
    private Quanlytaikhoan.component.TextFieldSuggestion textFieldSuggestion1;
    private Quanlytaikhoan.component.TextFieldSuggestion textFieldSuggestion10;
    private Quanlytaikhoan.component.TextFieldSuggestion textFieldSuggestion2;
    private Quanlytaikhoan.component.TextFieldSuggestion textFieldSuggestion3;
    private Quanlytaikhoan.component.TextFieldSuggestion textFieldSuggestion4;
    private Quanlytaikhoan.component.TextFieldSuggestion textFieldSuggestion5;
    private Quanlytaikhoan.component.TextFieldSuggestion textFieldSuggestion6;
    private Quanlytaikhoan.component.TextFieldSuggestion textFieldSuggestion7;
    private Quanlytaikhoan.component.TextFieldSuggestion textFieldSuggestion8;
    private Quanlytaikhoan.component.TextFieldSuggestion textFieldSuggestion9;
    private Quanlytaikhoan.component.TextField txtEmail;
    private Quanlytaikhoan.component.TextField txtIdNV;
    private Quanlytaikhoan.component.TextField txtName;
    private Quanlytaikhoan.component.TextField txtSDT;
    private Quanlytaikhoan.component.TextField txtTenNV;
    private Quanlytaikhoan.component.TextField txtmail;
    private Quanlytaikhoan.component.TextField txtsdt;
    private Quanlytaikhoan.component.TextField txttuoi;
    // End of variables declaration//GEN-END:variables
}
